import { Amplify } from 'aws-amplify';

try {
  // amplify_outputs.json is generated by 'npx ampx sandbox' — gitignored per environment
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const outputs = require('../amplify_outputs.json');
  Amplify.configure(outputs);
} catch {
  console.warn(
    '[Amplify] amplify_outputs.json not found.\n' +
    'Run "npx ampx sandbox" inside the mobile/ folder to generate it.'
  );
}
